version: '3'

services:
  database:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
